// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSUaM_2f7NiWU-L4hoYB9QbdT0g0hG0z4',
    appId: '1:190094519722:web:3788f6395f001f24f60fd3',
    messagingSenderId: '190094519722',
    projectId: 'chatapp-41015',
    authDomain: 'chatapp-41015.firebaseapp.com',
    storageBucket: 'chatapp-41015.appspot.com',
    measurementId: 'G-69TNH21PS3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnoDxeS-xh9WLq2OJUwtKbf37iiFPk4uA',
    appId: '1:190094519722:android:4cd7de5d0f6f6cfbf60fd3',
    messagingSenderId: '190094519722',
    projectId: 'chatapp-41015',
    storageBucket: 'chatapp-41015.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8RnYB0hyUDewG4AskfZXxovbLHflZ6Z8',
    appId: '1:190094519722:ios:02bcde8a7dd08779f60fd3',
    messagingSenderId: '190094519722',
    projectId: 'chatapp-41015',
    storageBucket: 'chatapp-41015.appspot.com',
    iosBundleId: 'com.example.akChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8RnYB0hyUDewG4AskfZXxovbLHflZ6Z8',
    appId: '1:190094519722:ios:02bcde8a7dd08779f60fd3',
    messagingSenderId: '190094519722',
    projectId: 'chatapp-41015',
    storageBucket: 'chatapp-41015.appspot.com',
    iosBundleId: 'com.example.akChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSUaM_2f7NiWU-L4hoYB9QbdT0g0hG0z4',
    appId: '1:190094519722:web:86780164c1343a36f60fd3',
    messagingSenderId: '190094519722',
    projectId: 'chatapp-41015',
    authDomain: 'chatapp-41015.firebaseapp.com',
    storageBucket: 'chatapp-41015.appspot.com',
    measurementId: 'G-HHMJG3KQLT',
  );

}